# Generated by Django 5.2.5 on 2025-12-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ImageField(null=True, upload_to='review_pics/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_by_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to='users.profile'),
        ),
    ]
