# Generated by Django 5.2.5 on 2025-12-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ImageField(null=True, upload_to='review_pics/'),
        ),
    ]
