# Generated by Django 5.2.5 on 2026-01-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_joblisting_images_alter_review_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
