# Generated by Django 5.2.5 on 2026-01-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_jobreport_profilereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreport',
            name='reporter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
