# Generated by Django 5.2.5 on 2026-01-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_jobreport_reporter_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereport',
            name='reporter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
