# Generated by Django 5.2.5 on 2026-02-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='open', max_length=10),
        ),
    ]
