# Generated by Django 5.2.5 on 2026-03-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_message_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam'), ('fake', 'Fake'), ('harassment', 'Harassment'), ('inappropiate', 'Inappropriate Content'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reported_convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_against', to='users.conversation')),
                ('reporter_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to='users.profile')),
            ],
        ),
    ]
