# Generated by Django 5.2.5 on 2026-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('garbage_removal', 'Garbage Removal'), ('automotive', 'Automotive'), ('handyman', 'Handyman'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
