# Generated by Django 5.2.5 on 2026-04-06 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_joblisting_title_alter_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='images',
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_pics/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.joblisting')),
            ],
        ),
    ]
