# Generated by Django 5.2.5 on 2026-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_joblisting_images_jobimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('garbage_removal', 'Garbage Removal'), ('automotive', 'Automotive'), ('handyman', 'Handyman'), ('other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Open', max_length=10),
        ),
    ]
