# Generated by Django 5.2.5 on 2026-04-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_joblisting_category_alter_joblisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed'), ('closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
