# Generated by Django 5.2.5 on 2026-04-21 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_jobapplication_status_alter_joblisting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreport',
            name='reported_job',
        ),
        migrations.RemoveField(
            model_name='jobreport',
            name='reporter_profile',
        ),
        migrations.RemoveField(
            model_name='profilereport',
            name='reported_profile',
        ),
        migrations.RemoveField(
            model_name='profilereport',
            name='reporter_profile',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='reported_review',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='reporter_profile',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('job', 'Job'), ('profile', 'Profile'), ('conversation', 'Conversation'), ('review', 'Review')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConversationReport',
        ),
        migrations.DeleteModel(
            name='JobReport',
        ),
        migrations.DeleteModel(
            name='ProfileReport',
        ),
        migrations.DeleteModel(
            name='ReviewReport',
        ),
    ]
