# Generated by Django 5.2.5 on 2026-04-21 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0040_remove_jobreport_reported_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
