# Generated by Django 5.2.5 on 2026-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_report_report_type_report_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('moving', 'Moving & Hauling'), ('automotive', 'Automotive'), ('handyman', 'Handyman'), ('delivery', 'Delivery'), ('other', 'Other')], default='Other', max_length=50),
        ),
    ]
