# Generated by Django 5.2.5 on 2026-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_joblisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('moving', 'Moving & Hauling'), ('automotive', 'Automotive'), ('handyman', 'Handyman'), ('delivery', 'Delivery'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
