# Generated by Django 5.2.5 on 2026-06-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_joblisting_description_alter_joblisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='due_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
