# Generated by Django 5.2.5 on 2026-07-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_joblisting_due_date_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='related_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.review'),
        ),
    ]
