# Generated by Django 5.2.5 on 2026-07-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_contactmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
