# Generated by Django 5.2.5 on 2026-07-25 03:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_rename_report_type_feedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
