# Generated by Django 5.2.5 on 2026-08-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_profile_email_verification_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='active',
        ),
    ]
