# Generated by Django 5.2.5 on 2025-12-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='images',
            field=models.ImageField(null=True, upload_to='job_pics/'),
        ),
    ]
