# Generated by Django 5.2.5 on 2025-12-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_joblisting_description_alter_joblisting_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
