# Generated by Django 5.2.5 on 2025-12-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_review_images_alter_review_review_by_profile_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('review_by_profile', 'review_to_profile'), name='one_review_per_user_per_profile'),
        ),
    ]
