# Generated by Django 5.2.5 on 2025-12-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_review_one_review_per_user_per_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_user_per_profile',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('review_by_profile', 'review_to_profile'), name='one_review_per_user_per_profile'),
        ),
    ]
