# Generated by Django 5.2.5 on 2025-12-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='review_pics/'),
        ),
    ]
