# Generated by Django 5.2.5 on 2025-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_review_images'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_user_per_profile',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_by_profile',
            new_name='review_received',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_to_profile',
            new_name='review_written',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('review_received', 'review_written'), name='one_review_per_user_per_profile'),
        ),
    ]
