# Generated by Django 5.2.5 on 2025-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_review_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='job_pics/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='review_pics/'),
        ),
    ]
