# Generated by Django 5.2.5 on 2026-01-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
