# Generated by Django 5.2.5 on 2026-01-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_joblisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam/Fraud'), ('fake', 'Fake Job'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profilereport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam/Fraud'), ('fake', 'Fake Profile'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam/Fraud'), ('fake', 'Fake Review'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reported_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_against', to='users.review')),
                ('reporter_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_made', to='users.profile')),
            ],
        ),
    ]
