# Generated by Django 5.2.5 on 2026-02-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_jobreport_reason_alter_profilereport_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
