# Generated by Django 5.2.5 on 2026-03-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='type',
        ),
        migrations.AddField(
            model_name='feedback',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feedback', 'Feedback'), ('suggestion', 'Suggestion')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
